Assignment11Bmake: HashTable.cpp HashTable.h ChainedHT.cpp ChainedHT.h HashEntry.h HashNode.h HashTests.cpp HashTests.h LinearProbeHT.cpp LinearProbeHT.h OpenAddressHT.cpp OpenAddressHT.h QuadraticProbeHT.cpp QuadraticProbeHT.h
	g++ -o Assignment11Bmake HashTable.cpp ChainedHT.cpp HashTests.cpp LinearProbeHT.cpp OpenAddressHT.cpp QuadraticProbeHT.cpp -I.

